#!/usr/bin/env python3
# Based on Chris Woodfield's example

from pygnmi.client import gNMIclient
from pprint import pprint
# Variables
eos = ('clab-team03-ceos1', 6030)
srl = ('clab-team03-srl2', 57400)
# Body
if __name__ == '__main__':
    print('#### EOS ####')
    with gNMIclient(target=eos, username='admin', password='admin', insecure=True) as gc:
        capabilities = gc.capabilities()
        interface = gc.get(path=['/interfaces/interface[name=*]/subinterfaces/subinterface[index=*]/ipv4/addresses/address/config/ip'])
    print('gNMI version: ', capabilities['gnmi_version'])
    print('Get interfaces:')
    pprint(interface)

    print('\n#### SR Linux ####')
    with gNMIclient(target=srl, username='admin', password='admin', insecure=False) as gc:
        capabilities = gc.capabilities()
        hostname = gc.get(path=['/system/name/host-name'], encoding='json_ietf')
        #interface = gc.get(path=['/interface/interface[name=*]/subinterfaces/subinterface[index=*]/ipv4/addresses/address/config/ip'])
        interface = gc.get(path=['/ietf-interfaces/interface[name=*]/subinterfaces/subinterface[index=*]/ipv4/addresses/address/config/ip'])
    print('gNMI version: ', capabilities['gnmi_version'])
    print('Get /system/name/host-name: ', hostname)
    print('Get interfaces:')
    pprint(interface)
